export const videos: IYouTubeVideo[] = [
  {
    id: "1",
    title: "How to Structure a YouTube Video",
    description: "Step-by-step guide to structuring your YouTube videos for maximum engagement.",
    thumbnailUrl: "https://img.youtube.com/vi/k0VOchBlqiQ/hqdefault.jpg",
    uploadDate: "2024-01-10T12:00:00Z",
    duration: "PT8M12S",
    YoutubeId: "k0VOchBlqiQ",
    views: 120000,
  },
  {
    id: "2",
    title: "TypeScript Objects, Arrays, Tuples & Enums | Basics Tutorial",
    description: "Learn the basics of objects, arrays, tuples, and enums in TypeScript.",
    thumbnailUrl: "https://img.youtube.com/vi/45zq0Xct-Oc/hqdefault.jpg",
    uploadDate: "2024-02-15T09:30:00Z",
    duration: "PT10M45S",
    YoutubeId: "45zq0Xct-Oc",
    views: 95000,
  },
  {
    id: "3",
    title: "Create and Apply an Interface to an Array in TypeScript",
    description: "How to define and use interfaces for arrays of objects in TypeScript.",
    thumbnailUrl: "https://img.youtube.com/vi/DZWNMjhj-VY/hqdefault.jpg",
    uploadDate: "2024-03-01T14:20:00Z",
    duration: "PT7M30S",
    YoutubeId: "DZWNMjhj-VY",
    views: 48000,
  },
  {
    id: "4",
    title: "Maximo Masterclass | Object Structure - Part 1",
    description: "Introduction to object structures in Maximo Integration Framework.",
    thumbnailUrl: "https://img.youtube.com/vi/VrSJhTGMM90/hqdefault.jpg",
    uploadDate: "2024-03-12T16:00:00Z",
    duration: "PT12M5S",
    YoutubeId: "VrSJhTGMM90",
    views: 32000,
  },
  {
    id: "5",
    title: "How Influencers Structure Long-Form YouTube Content",
    description: "A breakdown of long-form YouTube content structure and best practices.",
    thumbnailUrl: "https://img.youtube.com/vi/5A5FFyX50cw/hqdefault.jpg",
    uploadDate: "2024-04-05T11:00:00Z",
    duration: "PT15M20S",
    YoutubeId: "5A5FFyX50cw",
    views: 72000,
  },
  {
    id: "6",
    title: "How-To Add Video Structured Data to YouTube Embeds",
    description: "A step-by-step lesson for inserting VideoObject JSON-LD script for YouTube video embeds.",
    thumbnailUrl: "https://img.youtube.com/vi/It-cdZ78QNs/hqdefault.jpg",
    uploadDate: "2024-04-20T10:00:00Z",
    duration: "PT6M18S",
    YoutubeId: "It-cdZ78QNs",
    views: 21000,
  },
  // ... 14 more objects with similar structure
  {
    id: "7",
    title: "Understanding TypeScript Generics",
    description: "A beginner's guide to generics in TypeScript.",
    thumbnailUrl: "https://img.youtube.com/vi/abcdefg7/hqdefault.jpg",
    uploadDate: "2024-05-01T13:00:00Z",
    duration: "PT9M10S",
    YoutubeId: "abcdefg7",
    views: 34000,
  },
  {
    id: "8",
    title: "Top 5 TypeScript Tips for Beginners",
    description: "Essential TypeScript tips every beginner should know.",
    thumbnailUrl: "https://img.youtube.com/vi/abcdefg8/hqdefault.jpg",
    uploadDate: "2024-05-03T15:00:00Z",
    duration: "PT5M50S",
    YoutubeId: "abcdefg8",
    views: 27000,
  },
  {
    id: "9",
    title: "Async/Await in TypeScript Explained",
    description: "Learn how to use async/await in TypeScript for better asynchronous code.",
    thumbnailUrl: "https://img.youtube.com/vi/abcdefg9/hqdefault.jpg",
    uploadDate: "2024-05-06T18:00:00Z",
    duration: "PT8M40S",
    YoutubeId: "abcdefg9",
    views: 41000,
  },
  {
    id: "10",
    title: "React with TypeScript: Getting Started",
    description: "How to set up and use React with TypeScript.",
    thumbnailUrl: "https://img.youtube.com/vi/abcdefgh10/hqdefault.jpg",
    uploadDate: "2024-05-08T20:00:00Z",
    duration: "PT11M25S",
    YoutubeId: "abcdefgh10",
    views: 53000,
  },
  {
    id: "11",
    title: "TypeScript vs JavaScript: Key Differences",
    description: "A comparison of TypeScript and JavaScript for developers.",
    thumbnailUrl: "https://img.youtube.com/vi/abcdefgh11/hqdefault.jpg",
    uploadDate: "2024-05-10T09:00:00Z",
    duration: "PT7M15S",
    YoutubeId: "abcdefgh11",
    views: 68000,
  },
  {
    id: "12",
    title: "Building REST APIs with TypeScript",
    description: "A practical guide to building REST APIs using TypeScript.",
    thumbnailUrl: "https://img.youtube.com/vi/abcdefgh12/hqdefault.jpg",
    uploadDate: "2024-05-12T11:00:00Z",
    duration: "PT13M40S",
    YoutubeId: "abcdefgh12",
    views: 29000,
  },
  {
    id: "13",
    title: "TypeScript Interfaces Explained",
    description: "Everything you need to know about interfaces in TypeScript.",
    thumbnailUrl: "https://img.youtube.com/vi/abcdefgh13/hqdefault.jpg",
    uploadDate: "2024-05-14T14:00:00Z",
    duration: "PT6M55S",
    YoutubeId: "abcdefgh13",
    views: 37000,
  },
  {
    id: "14",
    title: "TypeScript for Node.js Developers",
    description: "How to use TypeScript effectively in Node.js projects.",
    thumbnailUrl: "https://img.youtube.com/vi/abcdefgh14/hqdefault.jpg",
    uploadDate: "2024-05-16T17:00:00Z",
    duration: "PT8M30S",
    YoutubeId: "abcdefgh14",
    views: 44000,
  },
  {
    id: "15",
    title: "TypeScript Advanced Types",
    description: "A deep dive into advanced types in TypeScript.",
    thumbnailUrl: "https://img.youtube.com/vi/abcdefgh15/hqdefault.jpg",
    uploadDate: "2024-05-18T19:00:00Z",
    duration: "PT10M00S",
    YoutubeId: "abcdefgh15",
    views: 36000,
  },
  {
    id: "16",
    title: "TypeScript Decorators Explained",
    description: "Learn about decorators in TypeScript and how to use them.",
    thumbnailUrl: "https://img.youtube.com/vi/abcdefgh16/hqdefault.jpg",
    uploadDate: "2024-05-20T21:00:00Z",
    duration: "PT7M45S",
    YoutubeId: "abcdefgh16",
    views: 25000,
  },
  {
    id: "17",
    title: "Migrating JavaScript Projects to TypeScript",
    description: "Best practices for migrating existing JavaScript codebases to TypeScript.",
    thumbnailUrl: "https://img.youtube.com/vi/abcdefgh17/hqdefault.jpg",
    uploadDate: "2024-05-22T23:00:00Z",
    duration: "PT12M10S",
    YoutubeId: "abcdefgh17",
    views: 31000,
  },
  {
    id: "18",
    title: "TypeScript Error Handling Patterns",
    description: "Effective error handling techniques in TypeScript.",
    thumbnailUrl: "https://img.youtube.com/vi/abcdefgh18/hqdefault.jpg",
    uploadDate: "2024-05-24T08:00:00Z",
    duration: "PT9M55S",
    YoutubeId: "abcdefgh18",
    views: 28000,
  },
  {
    id: "19",
    title: "TypeScript Utility Types",
    description: "An overview of utility types in TypeScript and how to use them.",
    thumbnailUrl: "https://img.youtube.com/vi/abcdefgh19/hqdefault.jpg",
    uploadDate: "2024-05-26T10:00:00Z",
    duration: "PT6M35S",
    YoutubeId: "abcdefgh19",
    views: 22000,
  },
  {
    id: "20",
    title: "TypeScript Project Setup from Scratch",
    description: "A beginner-friendly guide to setting up a new TypeScript project.",
    thumbnailUrl: "https://img.youtube.com/vi/abcdefgh20/hqdefault.jpg",
    uploadDate: "2024-05-27T12:00:00Z",
    duration: "PT8M20S",
    YoutubeId: "abcdefgh20",
    views: 39000,
  },
];

export interface IYouTubeVideo {
  id: string;
  title: string;
  description: string;
  thumbnailUrl: string;
  uploadDate: string; // ISO 8601 date string
  duration: string;   // ISO 8601 duration, e.g., "PT5M30S"
  YoutubeId: string;
  views: number;
}